#pragma once
#define POCZATEK_X 40
#define POCZATEK_Y 0
#define ODS_Y 2
#define ODS_X 4
#define POCZATEK_PLANSZY_X 49
#define POCZATEK_PLANSZY_Y 4
#define POCZATEK_MENU_Y 1
#define POCZATEK_MENU_X 2
#define POCZATEK_KOMUNIKATOW_X 29
#define POCZATEK_KOMUNIKATOW_Y 4
#define MAX_DL_KOMUNIKAT 18
#define LICZBA_ORGANIMZOW 10
#define KURSOR_GORA 0x48
#define KURSOR_DOL 0x50
#define KURSOR_PRAWO 0x4d
#define KURSOR_LEWO 0x4b
#define MOC 'p'
#define ZAPISZ 's'
#define WCZYTAJ 'r'
#define POCZATEK_ROZNE_Y 17
#define DL_LEGENDA 25
#define POCZATEK_STEROWANIA_Y 20
#define POCZATEK_KONCA_X 29
#define POCZATEK_KONCA_Y 2
#define NIE_DOTYCZY '0'
#define NOWA_GRA 'n'
#define OPUSC_GRE 'q'
#define MAX_KOM 26
